### ISSUE TITLE
Can't seem to get it to work in Ubuntu 22.04

### ISSUE THREAD

**Issue by mbze430** [inventage/certbot-dns-cloudns#6]
```
 pip install certbot-dns-cloudns --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: certbot-dns-cloudns in ./.local/lib/python3.12/site-packages (0.6.0)
Requirement already satisfied: acme<2.8.0,>=2.7.4 in ./.local/lib/python3.12/site-packages (from certbot-dns-cloudns) (2.7.4)
Requirement already satisfied: certbot<2.8.0,>=2.7.4 in ./.local/lib/python3.12/site-packages (from certbot-dns-cloudns) (2.7.4)
Requirement already satisfied: cloudns-api==0.9.3 in ./.local/lib/python3.12/site-packages (from certbot-dns-cloudns) (0.9.3)
Requirement already satisfied: dnspython<3.0.0,>=2.3.0 in ./.local/lib/python3.12/site-packages (from certbot-dns-cloudns) (2.6.1)
Requirement already satisfied: zope.interface>=5.4.0 in /usr/lib/python3/dist-packages (from certbot-dns-cloudns) (6.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from cloudns-api==0.9.3->certbot-dns-cloudns) (2.31.0)
Requirement already satisfied: cryptography>=3.2.1 in /usr/lib/python3/dist-packages (from acme<2.8.0,>=2.7.4->certbot-dns-cloudns) (41.0.7)
Requirement already satisfied: josepy>=1.13.0 in /usr/lib/python3/dist-packages (from acme<2.8.0,>=2.7.4->certbot-dns-cloudns) (1.14.0)
Requirement already satisfied: PyOpenSSL!=23.1.0,>=17.5.0 in /usr/lib/python3/dist-packages (from acme<2.8.0,>=2.7.4->certbot-dns-cloudns) (23.2.0)
Requirement already satisfied: pyrfc3339 in /usr/lib/python3/dist-packages (from acme<2.8.0,>=2.7.4->certbot-dns-cloudns) (1.1)
Requirement already satisfied: pytz>=2019.3 in /usr/lib/python3/dist-packages (from acme<2.8.0,>=2.7.4->certbot-dns-cloudns) (2024.1)
Requirement already satisfied: setuptools>=41.6.0 in /usr/lib/python3/dist-packages (from acme<2.8.0,>=2.7.4->certbot-dns-cloudns) (68.1.2)
Requirement already satisfied: ConfigArgParse>=1.5.3 in /usr/lib/python3/dist-packages (from certbot<2.8.0,>=2.7.4->certbot-dns-cloudns) (1.7)
Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python3/dist-packages (from certbot<2.8.0,>=2.7.4->certbot-dns-cloudns) (5.0.8)
Requirement already satisfied: distro>=1.0.1 in /usr/lib/python3/dist-packages (from certbot<2.8.0,>=2.7.4->certbot-dns-cloudns) (1.9.0)
Requirement already satisfied: parsedatetime>=2.4 in /usr/lib/python3/dist-packages (from certbot<2.8.0,>=2.7.4->certbot-dns-cloudns) (2.6)
johnny@proxy:~$ sudo certbot certonly --authenticator dns-cloudns
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested dns-cloudns plugin does not appear to be installed
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```
any recommendation or what I am doing wrong?

**Comment by heapoutofspace** [comment]
Hi,

It looks like the python version running certbot might not match the one you're using to install the authenticator plugin, or at least it can't find the package installed in `./.local/lib/python3.12/site-packages`. Try running certbot with the `-v` option to get a bit more info. Feel free to report back with the new output and the contents of `/var/log/letsencrypt/letsencrypt.log` and I will have another look.

**Comment by mbze430** [comment]
I ran pip install certbot-dns-cloudns with sudo and now it works...
But now I am getting this error.
 sudo certbot certonly --authenticator dns-cloudns --dns-cloudns-credentials ~/.secrets/certbot/cloudns.ini -d misery.dns-dynamic.netSaving debug log to /var/log/letsencrypt/letsencrypt.logEnter email address (used for urgent renewal and security notices) (Enter 'c' to cancel): ***@***.***
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -Please read the Terms of Service athttps://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf. You must agree inorder to register with the ACME server. Do you agree?- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -(Y)es/(N)o: Y
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -Would you be willing, once your first certificate is successfully issued, toshare your email address with the Electronic Frontier Foundation, a foundingpartner of the Let's Encrypt project and the non-profit organization thatdevelops Certbot? We'd like to send you email about our work encrypting the web,EFF news, campaigns, and ways to support digital freedom.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -(Y)es/(N)o: NAccount registered.Requesting a certificate for misery.dns-dynamic.netUnsafe permissions on credentials configuration file: /home/johnny/.secrets/certbot/cloudns.iniError communicating with the ClouDNS API: {'status_code': 200, 'success': False, 'payload': {'status': 'Failed', 'status_description': "You don't have access to the HTTP API. Check your plan."}, 'error': "You don't have access to the HTTP API. Check your plan."}Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

    On Friday, May 17, 2024 at 10:12:57 AM CDT, Simon Marti ***@***.***> wrote:  
 
 


Hi,

It looks like the python version running certbot might not match the one you're using to install the authenticator plugin, or at least it can't find the package installed in ./.local/lib/python3.12/site-packages. Try running certbot with the -v option to get a bit more info. Feel free to report back with the new output and the contents of /var/log/letsencrypt/letsencrypt.log and I will have another look.

**Comment by heapoutofspace** [comment]
Looks like you have a ClouDNS free tier account, which isn't eligible to use the HTTP API. See https://www.cloudns.net/premium
