### ISSUE TITLE
Requires OLD version of acme client

### ISSUE THREAD

**Issue by jnix85** [inventage/certbot-dns-cloudns#8]
This needs to be updated so it will support the current version of the acme client.

Currently this only works with 2.7.4 and earlier versions of acme, where the current version is 2.11.0

**Comment by tedski** [comment]
#7 will address this.

**Comment by heapoutofspace** [comment]
A new version [0.7.0](https://pypi.org/project/certbot-dns-cloudns/0.7.0/) is now available that includes acme version 2.11.0.
